# -*- coding: utf-8 -*-
"""cv_poaching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dN8XDzmNyV4Sbwsy4PgLkpXNvY9XwgC
"""

!pip install ultralytics opencv-python

from ultralytics import YOLO
import cv2
import numpy as np
import os
from google.colab import files
from IPython.display import Image, display

model = YOLO('yolov8n.pt')

def detect_eyes(image_path):
    try:
        results = model(image_path)
        eyes_detected = False
        for result in results:
            if result.boxes is not None and len(result.boxes) > 0:
                for box in result.boxes:
                    class_id = int(box.cls[0])
                    if class_id == 39:  # Person
                        continue
                    if class_id == 0 or class_id == 1:
                        continue
                    eyes_detected = True
                    break
        return eyes_detected

    except Exception as e:
        print(f"Error detecting eyes: {e}")
        return False

def predict_poaching_yolo(image_path):
    eyes_detected = detect_eyes(image_path)

    if eyes_detected:
        return "No Poaching Detected"
    else:
        return "Poaching Detected"

uploaded = files.upload()
for fn in uploaded.keys():
    prediction = predict_poaching_yolo(fn)
    print(f"Image: {fn}")
    print(f"Prediction: {prediction}")

    try:
        display(Image(fn))
    except FileNotFoundError:
        print(f"Error: Could not display image {fn}")
    except Exception as e:
        print(f"An error occurred while displaying the image: {e}")